apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: asleep-meerkat-python 
  janus-idp.io/tekton: asleep-meerkat-python
  backstage.io/kubernetes-id: asleep-meerkat-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: asleep-meerkat-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  